// src/components/rehab/patient-profile/TherapyTab.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import { TherapySession } from '@/types/rehab';
import { getTherapySessions, addTherapySession, updateTherapySession } from '@/lib/rehab/patients';
import { Loader2, Plus, Calendar, FileText, Edit } from 'lucide-react';
import { toast } from 'react-hot-toast';
import { formatDateDMY } from '@/lib/utils';
import { BrutalistCalendar } from '@/components/ui';

export default function TherapyTab({ patientId, session, dateFilter, readOnly = false }: { patientId: string, session: any, dateFilter?: { admissionDate: any; dischargeDate?: any } | null, readOnly?: boolean }) {
  const [sessions, setSessions] = useState<TherapySession[]>([]);
  const [loading, setLoading] = useState(true);
  const [showAddModal, setShowAddModal] = useState(false);
  const [editingSession, setEditingSession] = useState<TherapySession | null>(null);
  const [saving, setSaving] = useState(false);

  const isSessionInFilter = useCallback((sessionDateStr: string) => {
    if (!dateFilter) return true;
    const d = new Date(sessionDateStr + 'T00:00:00');

    let start = dateFilter.admissionDate;
    if (start) {
      if (typeof start.toDate === 'function') start = start.toDate();
      else start = new Date(start);
      start.setHours(0, 0, 0, 0);
    }

    let end = dateFilter.dischargeDate;
    if (end) {
      if (typeof end.toDate === 'function') end = end.toDate();
      else end = new Date(end);
      end.setHours(23, 59, 59, 999);
    }

    if (start && d < start) return false;
    if (end && d > end) return false;
    return true;
  }, [dateFilter]);

  const filteredSessions = useMemo(() => {
    return sessions.filter(s => isSessionInFilter(s.date));
  }, [sessions, isSessionInFilter]);

  // Form states
  const [sessionNotes, setSessionNotes] = useState('');
  const [sessionDate, setSessionDate] = useState(() => new Date().toISOString().split('T')[0]);
  const [editNotes, setEditNotes] = useState('');
  const [editDate, setEditDate] = useState('');

  const fetchSessions = useCallback(async () => {
    try {
      setLoading(true);
      const data = await getTherapySessions(patientId);
      setSessions(data);
    } catch (error) {
      console.error("Error fetching therapy sessions", error);
      toast.error('Failed to load sessions');
    } finally {
      setLoading(false);
    }
  }, [patientId]);

  useEffect(() => {
    fetchSessions();
  }, [fetchSessions]);

  const handleAddSession = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!sessionNotes) {
      toast.error('Session notes are required');
      return;
    }

    try {
      setSaving(true);
      // Calc next session number
      const nextNum = sessions.length > 0 ? Math.max(...sessions.map(s => s.sessionNumber)) + 1 : 1;

      const newSession: TherapySession = {
        id: '', // Will be generated by Firestore
        patientId,
        sessionNumber: nextNum,
        date: sessionDate,
        sessionNotes,
        progressRating: 2, // default value
        createdBy: session.uid,
        createdAt: new Date(),
      };

      await addTherapySession(newSession);
      toast.success('Session added');
      setShowAddModal(false);
      setSessionNotes('');
      setSessionDate(new Date().toISOString().split('T')[0]);
      fetchSessions();
    } catch (error) {
      console.error("Add session error", error);
      toast.error('Failed to add session');
    } finally {
      setSaving(false);
    }
  };

  const handleEditSession = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!editingSession) return;
    if (!editNotes) {
      toast.error('Session notes are required');
      return;
    }

    try {
      setSaving(true);
      await updateTherapySession(editingSession.id, editNotes, editDate);
      toast.success('Session notes and date updated');
      setEditingSession(null);
      setEditNotes('');
      setEditDate('');
      fetchSessions();
    } catch (error) {
      console.error("Update session error", error);
      toast.error('Failed to update session');
    } finally {
      setSaving(false);
    }
  };

  if (loading) {
    return <div className="py-12 flex justify-center"><Loader2 className="animate-spin text-teal-600" /></div>;
  }

  return (
    <div className="space-y-6 animate-in fade-in duration-500 overflow-x-hidden w-full max-w-full">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 mb-4 border-b border-gray-100 pb-4">
        <h2 className="text-xl font-black text-gray-900">Individual Therapy Sessions</h2>
        {!readOnly && (
          <button
            onClick={() => setShowAddModal(true)}
            className="w-full sm:w-auto bg-teal-600 hover:bg-teal-700 text-white px-5 py-2.5 rounded-xl font-black text-sm flex items-center justify-center gap-2 shadow-lg shadow-teal-900/10 active:scale-95 transition-all"
          >
            <Plus size={16} /> Add Session
          </button>
        )}
      </div>

      {filteredSessions.length === 0 ? (
        <div className="text-center py-16 border-2 border-dashed border-gray-100 rounded-[2rem] bg-gray-50/30">
          <FileText className="w-16 h-16 text-gray-200 mx-auto mb-4" />
          <p className="text-gray-400 font-bold uppercase text-xs tracking-widest">No therapy sessions recorded</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 gap-4">
          {filteredSessions.map(s => (
            <div key={s.id} className="bg-white border border-gray-100 p-6 rounded-[2rem] shadow-sm hover:shadow-md transition-all">
              <div className="flex justify-between items-start mb-4">
                <div className="flex items-center gap-3">
                  <div className="bg-teal-50 text-teal-700 font-black text-lg w-12 h-12 rounded-xl flex items-center justify-center border border-teal-100 shadow-inner">
                    #{s.sessionNumber}
                  </div>
                  <div>
                    <div className="flex items-center gap-2 text-gray-500 text-sm font-bold mb-1">
                      <Calendar size={14} className="text-teal-500" />
                      {formatDateDMY(s.date)}
                    </div>
                  </div>
                </div>
                {!readOnly && (
                  <button
                    onClick={() => {
                      setEditingSession(s);
                      setEditNotes(s.sessionNotes);
                      setEditDate(s.date || new Date().toISOString().split('T')[0]);
                    }}
                    className="text-teal-600 hover:text-teal-700 bg-teal-50 hover:bg-teal-100 px-3 py-1.5 rounded-lg text-xs font-bold uppercase flex items-center gap-1.5 transition-all"
                  >
                    <Edit size={14} /> Edit
                  </button>
                )}
              </div>
              <div className="bg-gray-50 p-4 rounded-2xl text-sm text-gray-700 leading-relaxed border border-gray-100">
                {s.sessionNotes}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Add Session Modal */}
      {showAddModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-3xl shadow-xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-6 border-b border-gray-100 flex items-center justify-between">
              <h2 className="text-xl font-black text-gray-900">Add Therapy Session</h2>
              <button type="button" onClick={() => setShowAddModal(false)} className="text-gray-400 hover:bg-gray-100 p-2 rounded-xl">
                ✕
              </button>
            </div>
            <form onSubmit={handleAddSession} className="p-6 space-y-4">
              <div className="space-y-1.5">
                <BrutalistCalendar
                  label="Session Date *"
                  value={sessionDate}
                  onChange={setSessionDate}
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-400 uppercase tracking-widest mb-1.5">Session Notes *</label>
                <textarea required rows={5} value={sessionNotes} onChange={e => setSessionNotes(e.target.value)} className="w-full bg-gray-50 border border-gray-100 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-teal-500 outline-none resize-none" placeholder="Detailed notes about the therapy session..."></textarea>
              </div>

              <button type="submit" disabled={saving} className="w-full bg-teal-600 hover:bg-teal-700 text-white font-black py-4 rounded-2xl flex items-center justify-center gap-2 transition shadow-lg shadow-teal-100 disabled:opacity-70 mt-4">
                {saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Plus size={18} />}
                {saving ? 'Saving...' : 'Save Session'}
              </button>
            </form>
          </div>
        </div>
      )}

      {/* Edit Session Modal */}
      {editingSession && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-gray-900/60 backdrop-blur-sm">
          <div className="bg-white rounded-3xl shadow-xl w-full max-w-lg overflow-hidden animate-in fade-in zoom-in-95 duration-200">
            <div className="p-6 border-b border-gray-100 flex items-center justify-between">
              <h2 className="text-xl font-black text-gray-900">Edit Therapy Session #{editingSession.sessionNumber}</h2>
              <button type="button" onClick={() => setEditingSession(null)} className="text-gray-400 hover:bg-gray-100 p-2 rounded-xl">
                ✕
              </button>
            </div>
            <form onSubmit={handleEditSession} className="p-6 space-y-4">
              <div className="space-y-1.5">
                <BrutalistCalendar
                  label="Session Date *"
                  value={editDate}
                  onChange={setEditDate}
                />
              </div>
              <div>
                <label className="block text-xs font-black text-gray-400 uppercase tracking-widest mb-1.5">Session Notes *</label>
                <textarea required rows={5} value={editNotes} onChange={e => setEditNotes(e.target.value)} className="w-full bg-gray-50 border border-gray-100 rounded-xl px-4 py-3 text-sm focus:ring-2 focus:ring-teal-500 outline-none resize-none" placeholder="Update therapy session notes..."></textarea>
              </div>

              <button type="submit" disabled={saving} className="w-full bg-teal-600 hover:bg-teal-700 text-white font-black py-4 rounded-2xl flex items-center justify-center gap-2 transition shadow-lg shadow-teal-100 disabled:opacity-70 mt-4">
                {saving ? <Loader2 className="w-5 h-5 animate-spin" /> : <Edit size={18} />}
                {saving ? 'Saving...' : 'Update Notes'}
              </button>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
