// apps/web/src/scripts/distill-corrections.ts
import { adminDb } from '../lib/firebaseAdmin';
import { getCompletion } from '../lib/voice/aiProvider';

export async function distillCorrections() {
  console.log('[Distill Corrections] Starting nightly correction distillation...');
  
  try {
    // 1. Fetch memory entries where the user flagged wasCorrect == false
    const memorySnap = await adminDb.collection('ai_memory')
      .where('wasCorrect', '==', false)
      .get();
      
    if (memorySnap.empty) {
      console.log('[Distill Corrections] No corrections found. Exiting.');
      return;
    }
    
    const uncompiledCorrections = memorySnap.docs.map(doc => ({
      id: doc.id,
      ...doc.data()
    })).filter((m: any) => m.correction && String(m.correction).trim().length > 0);
    
    if (uncompiledCorrections.length === 0) {
      console.log('[Distill Corrections] No valid correction text found. Exiting.');
      return;
    }
    
    console.log(`[Distill Corrections] Found ${uncompiledCorrections.length} flagged corrections. Analyzing...`);

    // 2. Format a system prompt for Gemini explaining the task
    const systemPrompt = `
You are a database and AI logic compiler for the KhanHub ERP Voice Assistant.
Your task is to analyze a list of incorrect queries, their parsed intents, and the user's manual correction notes.
Distill these into a set of clean, actionable rules for each module, and return them as a valid JSON array.

=== OUTPUT JSON SCHEMA ===
[
  {
    "moduleId": "jobcenter" | "rehab" | "spims" | "hospital" | "sukoon" | "welfare" | "hq",
    "trigger": "Short description of what trigger words or topics this applies to",
    "correctBehavior": "Detailed instructions on how the intent parser should behave (e.g. which collections to target, camelCase vs snake_case names, etc.)"
  }
]

=== RULES FOR COMPILATION ===
- Group similar errors into a single rule if they target the same behavior.
- Be extremely precise with database collection names (e.g., job_center_transactions vs jobcenter_finance).
- Do not repeat rules that are already defined in the standard ERP system knowledge. Only record new corrections/behaviors learned from these failures.
`;

    const userMessage = `
Here are the incorrect queries and the corrections:
${JSON.stringify(uncompiledCorrections.map((c: any) => ({
  query: c.query,
  parsedIntent: c.parsedIntent,
  correction: c.correction
})), null, 2)}

Distill these into a JSON array matching the schema:
`;

    // 3. Request Gemini completion (since it's not latency-sensitive and Gemini has a larger free budget)
    // Force Gemini usage by setting jsonMode = true
    const response = await getCompletion({
      systemPrompt,
      userMessage,
      temperature: 0.1,
      jsonMode: true
    });
    
    const raw = response.text || '[]';
    const distilledRules = JSON.parse(raw);
    
    if (!Array.isArray(distilledRules) || distilledRules.length === 0) {
      console.log('[Distill Corrections] No rules generated by Gemini. Exiting.');
      return;
    }
    
    console.log(`[Distill Corrections] Distilled ${distilledRules.length} rules. Writing to firestore...`);
    
    // 4. Write/Update rules in firestore
    const batch = adminDb.batch();
    for (const rule of distilledRules) {
      if (!rule.moduleId || !rule.correctBehavior) continue;
      
      const key = `${rule.moduleId}_${String(rule.trigger || 'general').replace(/[^a-zA-Z0-9]/g, '_').toLowerCase()}`;
      const ref = adminDb.collection('ai_learned_corrections').doc(key);
      
      batch.set(ref, {
        moduleId: rule.moduleId,
        trigger: rule.trigger || 'general',
        correctBehavior: rule.correctBehavior,
        createdAt: new Date().toISOString(),
        learnedFromCount: uncompiledCorrections.length // metadata
      }, { merge: true });
    }
    
    await batch.commit();
    console.log('[Distill Corrections] Seeding complete! All learned corrections updated.');
    
  } catch (err) {
    console.error('[Distill Corrections] Failed to distill corrections:', err);
  }
}
